name: Practice_Workflow
on: push
jobs:
  practice_jobs:
    runs on: ubuntu-latest
    steps:
      - name: Checking out Repo
        uses: actions/checkout@v6
      - name: installing node jobs
        uses: actions/setup-node@v6
      - name: linting the code
        run: npm install eslint
      - name: running the tests
        run: npm test
      - name: building the code
        run: npm run build
