name: Practice_Workflow
on: push
jobs:
  practice_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Repo
        uses: actions/checkout@v6
      - name: Installing Node.js
        uses: actions/setup-node@v6
      - name: Linting the code
        run: npm install eslint
      - name: Running the tests
        run: npm test
      - name: Building the code
        run: npm run build
